### ISSUE TITLE
Consider renaming to @rdfjs/dataset-core

### ISSUE THREAD

**Issue by alexkreidler** [rdfjs-base/dataset#7]
Some users might be confused as this only implements the RDF/JS `DatasetCore` [interface](https://rdf.js.org/dataset-spec/#datasetcore-interface).

Or maybe just add a note in the README, and point users to `rdf-dataset-indexed` or `graphy` for a full `Dataset` interface implementation.

**Comment by bergos** [comment]
This package will implement the `Dataset` interface, once it's no longer experimental.
